### ISSUE TITLE
Add due date/time to projects

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-orbis#12]
https://wordpress.org/support/topic/add-due-time-and-assignee-to-projects?replies=1#post-6705381

> Dear Orbis
> Your plugin help me a lot for my website and project.
> But I have a small problem which I found way to resolve yet.
> I'd like to add Due time and Assignee person for 'Project' as well filter like with Task, is there anyway to do this ?
> Thank you for help me a lot.

**Comment by remcotolsma** [comment]
We have not received this request much more often and we do not immediately see the benefits of this in our own Orbis installation. A project may have a planned end date at the start, but in practice we see that this often turns out differently than planned.
